### ISSUE TITLE
Publishing fails with `registry validation failed for package 0`

### ISSUE THREAD

**Issue by habedi** [modelcontextprotocol/registry#531]
**Describe the bug**

I want to publish [this project](https://github.com/habedi/omni-lpr) to the MCP registry, but I get an error saying that the `mcp-name` is not included or available in the package README on PyPI. 

I'm not sure, but I think this error is a bug and shouldn't happen with my settings.

**To Reproduce**
1. Follow the instructions in [here](https://github.com/habedi/omni-lpr/tree/main/docs/github_mcp_registry).

**Expected behavior**

Publish should succeed.

**Logs**

```sh
mcp-publisher publish
Publishing to https://registry.modelcontextprotocol.io...
Error: publish failed: server returned status 400: {"title":"Bad Request","status":400,"detail":"Failed to publish server","errors":[{"message":"registry validation failed for package 0 (omni-lpr): PyPI package 'omni-lpr' ownership validation failed. The server name 'io.github.habedi/omni-lpr' must appear as 'mcp-name: io.github.habedi/omni-lpr' in the package README"}]}
```

**Additional context**

The `mcp-name` is set in the project's [pyproject.toml](https://github.com/habedi/omni-lpr/blob/main/pyproject.toml) (as a keyword) and is available on the package README on PyPI.

**Comment by Avish34** [comment]
Can you share your server.json? I can have a quick look.

**Comment by habedi** [comment]
> Can you share your server.json? I can have a quick look.

It's here: https://github.com/habedi/omni-lpr/blob/main/docs/github_mcp_registry/server.json

**Comment by Avish34** [comment]
Thanks. Let me check.

**Comment by Avish34** [comment]
Hey @habedi ,
The way we validate is `"mcp-name: {server_name}"`, but in your readme I can see it as ` mcp-name:io.github.habedi/omni-lpr`. It basically violates the convention we use. There should be a space after colon. You can try again after adding the space.
cc: @domdomegg

**Comment by domdomegg** [comment]
From a registry feature perspective, possibly we should allow it with/without the space to be more forgiving here? I don't mind too much either way.

**Comment by habedi** [comment]
> Hey [@habedi](https://github.com/habedi) , The way we validate is `"mcp-name: {server_name}"`, but in your readme I can see it as ` mcp-name:io.github.habedi/omni-lpr`. It basically violates the convention we use. There should be a space after colon. You can try again after adding the space. cc: [@domdomegg](https://github.com/domdomegg)

OK. Thanks.

I used `mcp-name:io.github.habedi/omni-lpr` based on the example I saw [here](https://github.com/domdomegg/time-mcp-pypi/blob/master/pyproject.toml). I think the example is inconsistent at the moment.

<img width="1315" height="663" alt="Image" src="https://github.com/user-attachments/assets/bbf2fcf3-f53c-4060-afda-6cc215ba3ed4" />

**Comment by Avish34** [comment]
@domdomegg can we also change the example?

**Comment by domdomegg** [comment]
Fixed, thanks! Removed from the keywords.

**Comment by habedi** [comment]
> Hey [@habedi](https://github.com/habedi) , The way we validate is `"mcp-name: {server_name}"`, but in your readme I can see it as ` mcp-name:io.github.habedi/omni-lpr`. It basically violates the convention we use. There should be a space after colon. You can try again after adding the space. cc: [@domdomegg](https://github.com/domdomegg)

I changed the `mcp-name:io.github.habedi/omni-lpr` to `mcp-name: io.github.habedi/omni-lpr` in the keyword list of the package and published it to PyPI.

I still see the error:

```
mcp-publisher publish
Publishing to https://registry.modelcontextprotocol.io...
Error: publish failed: server returned status 400: {"title":"Bad Request","status":400,"detail":"Failed to publish server","errors":[{"message":"registry validation failed for package 0 (omni-lpr): PyPI package 'omni-lpr' ownership validation failed. The server name 'io.github.habedi/omni-lpr' must appear as 'mcp-name: io.github.habedi/omni-lpr' in the package README"}]}
```

How can I include the `mcp-name: io.github.habedi/omni-lpr` on the package README? Should it be done manually? Is there a more robust way?

**Comment by pree-dew** [comment]
@habedi you can try adding something like this in your Readme, it won't be visible and will solve the problem. 

```
<!-- mcp-name: io.github.pree-dew/mcp-bookmark -->
```

**Comment by AshwanthramKL** [comment]
For anyone landing here later hitting the same 400 on a PyPI package:

The mechanism is now correctly documented at [Package Types § Ownership Verification for PyPI](https://github.com/modelcontextprotocol/registry/blob/main/docs/modelcontextprotocol-io/package-types.mdx#pypi-packages) — you want an `mcp-name: <server-name>` line (or an HTML comment `<!-- mcp-name: ... -->`) in the PyPI package's README.

I opened #1192 to signpost non-npm publishers from the quickstart so they don't have to debug this first. Two-line `<Note>` at the top + a better troubleshooting row — no content duplication.
